
listen_address = "0.0.0.0:8080"
threads = 4
headers = [
    "Remote-Email",
    "Remote-Groups",
    "Remote-Name",
    "Remote-User",
]
allow_list = [
    "127.0.0.1",
]
days = 0
hour = 6
minute = 1
prune_interval = 10